# Build Stage
FROM node:22-alpine AS builder

WORKDIR /app

# Copy package files from web subdirectory (Run form Root context)
COPY web/package*.json ./
RUN npm ci 

# Copy source code and build
COPY web/ .
RUN npm run build

# Server Stage
FROM nginx:alpine

# Copy build artifacts to Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy custom config (defined below)
COPY web/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]